// +build !ignore_autogenerated

/*
Copyright 2018 The Prohori Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	monitoring "github.com/prohori/prohori/pkg/apis/monitoring"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Check_To_monitoring_Check,
		Convert_monitoring_Check_To_v1alpha1_Check,
		Convert_v1alpha1_CheckList_To_monitoring_CheckList,
		Convert_monitoring_CheckList_To_v1alpha1_CheckList,
		Convert_v1alpha1_CheckSpec_To_monitoring_CheckSpec,
		Convert_monitoring_CheckSpec_To_v1alpha1_CheckSpec,
		Convert_v1alpha1_CheckStatus_To_monitoring_CheckStatus,
		Convert_monitoring_CheckStatus_To_v1alpha1_CheckStatus,
		Convert_v1alpha1_CheckStatusStrategy_To_monitoring_CheckStatusStrategy,
		Convert_monitoring_CheckStatusStrategy_To_v1alpha1_CheckStatusStrategy,
		Convert_v1alpha1_CheckStrategy_To_monitoring_CheckStrategy,
		Convert_monitoring_CheckStrategy_To_v1alpha1_CheckStrategy,
		Convert_v1alpha1_CommandPlugin_To_monitoring_CommandPlugin,
		Convert_monitoring_CommandPlugin_To_v1alpha1_CommandPlugin,
		Convert_v1alpha1_NotificationReceiver_To_monitoring_NotificationReceiver,
		Convert_monitoring_NotificationReceiver_To_v1alpha1_NotificationReceiver,
		Convert_v1alpha1_ObjectSelector_To_monitoring_ObjectSelector,
		Convert_monitoring_ObjectSelector_To_v1alpha1_ObjectSelector,
	)
}

func autoConvert_v1alpha1_Check_To_monitoring_Check(in *Check, out *monitoring.Check, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_CheckSpec_To_monitoring_CheckSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CheckStatus_To_monitoring_CheckStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Check_To_monitoring_Check is an autogenerated conversion function.
func Convert_v1alpha1_Check_To_monitoring_Check(in *Check, out *monitoring.Check, s conversion.Scope) error {
	return autoConvert_v1alpha1_Check_To_monitoring_Check(in, out, s)
}

func autoConvert_monitoring_Check_To_v1alpha1_Check(in *monitoring.Check, out *Check, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_monitoring_CheckSpec_To_v1alpha1_CheckSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_monitoring_CheckStatus_To_v1alpha1_CheckStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_monitoring_Check_To_v1alpha1_Check is an autogenerated conversion function.
func Convert_monitoring_Check_To_v1alpha1_Check(in *monitoring.Check, out *Check, s conversion.Scope) error {
	return autoConvert_monitoring_Check_To_v1alpha1_Check(in, out, s)
}

func autoConvert_v1alpha1_CheckList_To_monitoring_CheckList(in *CheckList, out *monitoring.CheckList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]monitoring.Check, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Check_To_monitoring_Check(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_CheckList_To_monitoring_CheckList is an autogenerated conversion function.
func Convert_v1alpha1_CheckList_To_monitoring_CheckList(in *CheckList, out *monitoring.CheckList, s conversion.Scope) error {
	return autoConvert_v1alpha1_CheckList_To_monitoring_CheckList(in, out, s)
}

func autoConvert_monitoring_CheckList_To_v1alpha1_CheckList(in *monitoring.CheckList, out *CheckList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Check, len(*in))
		for i := range *in {
			if err := Convert_monitoring_Check_To_v1alpha1_Check(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_monitoring_CheckList_To_v1alpha1_CheckList is an autogenerated conversion function.
func Convert_monitoring_CheckList_To_v1alpha1_CheckList(in *monitoring.CheckList, out *CheckList, s conversion.Scope) error {
	return autoConvert_monitoring_CheckList_To_v1alpha1_CheckList(in, out, s)
}

func autoConvert_v1alpha1_CheckSpec_To_monitoring_CheckSpec(in *CheckSpec, out *monitoring.CheckSpec, s conversion.Scope) error {
	out.Type = monitoring.CheckType(in.Type)
	out.Command = in.Command
	out.Flags = *(*map[string]string)(unsafe.Pointer(&in.Flags))
	out.Selector = (*monitoring.ObjectSelector)(unsafe.Pointer(in.Selector))
	if in.Plugin != nil {
		in, out := &in.Plugin, &out.Plugin
		*out = new(monitoring.CommandPlugin)
		if err := Convert_v1alpha1_CommandPlugin_To_monitoring_CommandPlugin(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Plugin = nil
	}
	out.CheckInterval = in.CheckInterval
	out.AlertInterval = in.AlertInterval
	out.NotifierSecretName = in.NotifierSecretName
	if in.Receivers != nil {
		in, out := &in.Receivers, &out.Receivers
		*out = make([]monitoring.NotificationReceiver, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_NotificationReceiver_To_monitoring_NotificationReceiver(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Receivers = nil
	}
	return nil
}

func Convert_v1alpha1_CheckSpec_To_monitoring_CheckSpec(in *CheckSpec, out *monitoring.CheckSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CheckSpec_To_monitoring_CheckSpec(in, out, s)
}

func autoConvert_monitoring_CheckSpec_To_v1alpha1_CheckSpec(in *monitoring.CheckSpec, out *CheckSpec, s conversion.Scope) error {
	out.Type = CheckType(in.Type)
	out.Command = in.Command
	out.Flags = *(*map[string]string)(unsafe.Pointer(&in.Flags))
	out.Selector = (*ObjectSelector)(unsafe.Pointer(in.Selector))
	if in.Plugin != nil {
		in, out := &in.Plugin, &out.Plugin
		*out = new(CommandPlugin)
		if err := Convert_monitoring_CommandPlugin_To_v1alpha1_CommandPlugin(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Plugin = nil
	}
	out.CheckInterval = in.CheckInterval
	out.AlertInterval = in.AlertInterval
	out.NotifierSecretName = in.NotifierSecretName
	if in.Receivers != nil {
		in, out := &in.Receivers, &out.Receivers
		*out = make([]NotificationReceiver, len(*in))
		for i := range *in {
			if err := Convert_monitoring_NotificationReceiver_To_v1alpha1_NotificationReceiver(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Receivers = nil
	}
	return nil
}

func Convert_monitoring_CheckSpec_To_v1alpha1_CheckSpec(in *monitoring.CheckSpec, out *CheckSpec, s conversion.Scope) error {
	return autoConvert_monitoring_CheckSpec_To_v1alpha1_CheckSpec(in, out, s)
}

func autoConvert_v1alpha1_CheckStatus_To_monitoring_CheckStatus(in *CheckStatus, out *monitoring.CheckStatus, s conversion.Scope) error {
	in.Phase = CheckPhase(out.Phase)
	return nil
}

// Convert_v1alpha1_AlertStatus_To_monitoring_AlertStatus is an autogenerated conversion function.
func Convert_v1alpha1_CheckStatus_To_monitoring_CheckStatus(in *CheckStatus, out *monitoring.CheckStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CheckStatus_To_monitoring_CheckStatus(in, out, s)
}

func autoConvert_monitoring_CheckStatus_To_v1alpha1_CheckStatus(in *monitoring.CheckStatus, out *CheckStatus, s conversion.Scope) error {
	in.Phase = monitoring.CheckPhase(out.Phase)
	return nil
}

// Convert_monitoring_AlertStatus_To_v1alpha1_AlertStatus is an autogenerated conversion function.
func Convert_monitoring_CheckStatus_To_v1alpha1_CheckStatus(in *monitoring.CheckStatus, out *CheckStatus, s conversion.Scope) error {
	return autoConvert_monitoring_CheckStatus_To_v1alpha1_CheckStatus(in, out, s)
}

func autoConvert_v1alpha1_CheckStatusStrategy_To_monitoring_CheckStatusStrategy(in *CheckStatusStrategy, out *monitoring.CheckStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_CheckStatusStrategy_To_monitoring_CheckStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_CheckStatusStrategy_To_monitoring_CheckStatusStrategy(in *CheckStatusStrategy, out *monitoring.CheckStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_CheckStatusStrategy_To_monitoring_CheckStatusStrategy(in, out, s)
}

func autoConvert_monitoring_CheckStatusStrategy_To_v1alpha1_CheckStatusStrategy(in *monitoring.CheckStatusStrategy, out *CheckStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_monitoring_CheckStatusStrategy_To_v1alpha1_CheckStatusStrategy is an autogenerated conversion function.
func Convert_monitoring_CheckStatusStrategy_To_v1alpha1_CheckStatusStrategy(in *monitoring.CheckStatusStrategy, out *CheckStatusStrategy, s conversion.Scope) error {
	return autoConvert_monitoring_CheckStatusStrategy_To_v1alpha1_CheckStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_CheckStrategy_To_monitoring_CheckStrategy(in *CheckStrategy, out *monitoring.CheckStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_CheckStrategy_To_monitoring_CheckStrategy is an autogenerated conversion function.
func Convert_v1alpha1_CheckStrategy_To_monitoring_CheckStrategy(in *CheckStrategy, out *monitoring.CheckStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_CheckStrategy_To_monitoring_CheckStrategy(in, out, s)
}

func autoConvert_monitoring_CheckStrategy_To_v1alpha1_CheckStrategy(in *monitoring.CheckStrategy, out *CheckStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_monitoring_CheckStrategy_To_v1alpha1_CheckStrategy is an autogenerated conversion function.
func Convert_monitoring_CheckStrategy_To_v1alpha1_CheckStrategy(in *monitoring.CheckStrategy, out *CheckStrategy, s conversion.Scope) error {
	return autoConvert_monitoring_CheckStrategy_To_v1alpha1_CheckStrategy(in, out, s)
}

func autoConvert_v1alpha1_CommandPlugin_To_monitoring_CommandPlugin(in *CommandPlugin, out *monitoring.CommandPlugin, s conversion.Scope) error {
	out.PluginPullPolicy = monitoring.PullPolicy(in.PluginPullPolicy)
	out.Binary = in.Binary
	return nil
}

func Convert_v1alpha1_CommandPlugin_To_monitoring_CommandPlugin(in *CommandPlugin, out *monitoring.CommandPlugin, s conversion.Scope) error {
	return autoConvert_v1alpha1_CommandPlugin_To_monitoring_CommandPlugin(in, out, s)
}

func autoConvert_monitoring_CommandPlugin_To_v1alpha1_CommandPlugin(in *monitoring.CommandPlugin, out *CommandPlugin, s conversion.Scope) error {
	out.PluginPullPolicy = PullPolicy(in.PluginPullPolicy)
	out.Binary = in.Binary
	return nil
}

func Convert_monitoring_CommandPlugin_To_v1alpha1_CommandPlugin(in *monitoring.CommandPlugin, out *CommandPlugin, s conversion.Scope) error {
	return autoConvert_monitoring_CommandPlugin_To_v1alpha1_CommandPlugin(in, out, s)
}

func autoConvert_v1alpha1_NotificationReceiver_To_monitoring_NotificationReceiver(in *NotificationReceiver, out *monitoring.NotificationReceiver, s conversion.Scope) error {
	out.State = monitoring.CheckState(in.State)
	out.To = *(*[]string)(unsafe.Pointer(&in.To))
	out.Notifier = in.Notifier
	return nil
}

func Convert_v1alpha1_NotificationReceiver_To_monitoring_NotificationReceiver(in *NotificationReceiver, out *monitoring.NotificationReceiver, s conversion.Scope) error {
	return autoConvert_v1alpha1_NotificationReceiver_To_monitoring_NotificationReceiver(in, out, s)
}

func autoConvert_monitoring_NotificationReceiver_To_v1alpha1_NotificationReceiver(in *monitoring.NotificationReceiver, out *NotificationReceiver, s conversion.Scope) error {
	out.State = CheckState(in.State)
	out.To = *(*[]string)(unsafe.Pointer(&in.To))
	out.Notifier = in.Notifier
	return nil
}

func Convert_monitoring_NotificationReceiver_To_v1alpha1_NotificationReceiver(in *monitoring.NotificationReceiver, out *NotificationReceiver, s conversion.Scope) error {
	return autoConvert_monitoring_NotificationReceiver_To_v1alpha1_NotificationReceiver(in, out, s)
}

func autoConvert_v1alpha1_ObjectSelector_To_monitoring_ObjectSelector(in *ObjectSelector, out *monitoring.ObjectSelector, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.MatchLabels = *(*map[string]string)(unsafe.Pointer(&in.MatchLabels))
	return nil
}

// Convert_v1alpha1_ObjectSelector_To_monitoring_ObjectSelector is an autogenerated conversion function.
func Convert_v1alpha1_ObjectSelector_To_monitoring_ObjectSelector(in *ObjectSelector, out *monitoring.ObjectSelector, s conversion.Scope) error {
	return autoConvert_v1alpha1_ObjectSelector_To_monitoring_ObjectSelector(in, out, s)
}

func autoConvert_monitoring_ObjectSelector_To_v1alpha1_ObjectSelector(in *monitoring.ObjectSelector, out *ObjectSelector, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.MatchLabels = *(*map[string]string)(unsafe.Pointer(&in.MatchLabels))
	return nil
}

// Convert_monitoring_ObjectSelector_To_v1alpha1_ObjectSelector is an autogenerated conversion function.
func Convert_monitoring_ObjectSelector_To_v1alpha1_ObjectSelector(in *monitoring.ObjectSelector, out *ObjectSelector, s conversion.Scope) error {
	return autoConvert_monitoring_ObjectSelector_To_v1alpha1_ObjectSelector(in, out, s)
}
